### ISSUE TITLE
How to report a bug on github?

### ISSUE THREAD

**Issue by matematikaadit** [holman/feedback#152]
I've found a bug on github (gist actually). But I found nowhere to report it? Could you show me how to fill in an issue for github?

thanks before.

**Comment by AndersBillLinden** [comment]
When reporting an issue on github, you should be able to mark it as private. Meaning that only a selected few can read it (and know it is existing). This is not an "idea" but a requirement for how github can be used to report secuity problems.

**Comment by LukeLR** [comment]
Just found a bug in issue replying and looked for a way to publish it. Now I am very, *very* surprised, that an open-source-platform like GitHub doesn't provide just a simple bug tracker. Why require everyone writing an e-mail? Even if I just heard positive things on the GitHub support (and that's *really* positive, because most of today's support solutions just serve you with stupid calling queues and replys like "We're not covering your issue", "We'll pass that to the IT-department"), I think GitHub should change this. That's really a downside, and my faith on GitHub is now at least a bit  struck. Will publish an issue somewhere.

**Comment by holman** [comment]
Feel free to let them know that.

**Comment by hickford** [comment]
You can also use https://github.com/isaacs/github

> Issues and feature requests posted to GitHub are not stored in any publicly available location, so I find that I quickly lose track of the things that I've sent them.

**Comment by manjulacredr** [comment]
Hey,
I have found a bug wherein the update profile button doesnt update your selected picture.

Thanks
Manjula

**Comment by hickford** [comment]
See also https://github.com/dear-github/dear-github

**Comment by holman** [comment]
don't care
