### ISSUE TITLE
Why doesn't my Github profile show organizations that I belong?

### ISSUE THREAD

**Issue by knd** [holman/feedback#274]
They show up when I'm logged in my own account, but not from other users' views. What special situation am I falling into? Thanks.

**Comment by nonchris** [comment]
Since this was the first thing I found when googeling for a solution in 2021 I decided to leave an explanation for other people:  
- Got to your organizations page
- Go to the `people` tab
- Find yourself and click on your name
Now there's a display of your information on the left including `Membership [public | private]`.  
You should be able to click on this to get a drop-down menu which allows you to change the visibility in your profile. Done!  
_Note that it's possible for admins of an enterprise organization to turn this option of:_
https://docs.github.com/en/enterprise-server@3.0/admin/user-management/managing-organizations-in-your-enterprise/configuring-visibility-for-organization-membership

**Comment by ramiz03** [comment]
> They show up when I'm logged in my own account, but not from other users' views. What special situation am I falling into? Thanks.

same tbh. I see other people who are part of the same organization has their organization listed in their public profile but doesn't work for me :(

P.S.: it's visible to me when i'm logged in and see my profile

do lmk if someone can figure out what's the issue

**Comment by moshdev2213** [comment]
It seems the official GitHub docs have published some guide to be followed to resolve this problem ,  have a look in to this link

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership
