### ISSUE TITLE
Github Enterprise - Permission System

### ISSUE THREAD

**Issue by sts** [holman/feedback#455]
<i>We are currently evaluating GitHub enterprise, and I must admit I really liked the product from the first moment on. I still see a problem in your current permission system:</i>

GitHub is a company which is developing code internally, within a trusted and closed community, so you get the opportunity to allow everyone within that trusted circle to access all information.

Our company started 4 years ago, when we were only 4 people. We've gone through a vast growth period to around 40 people right now, and we still kept and wanna keep our initial spin to get work done well and fast. Thats one of essential ideas of evaluating Github enterprise, because the system supports and represents what we actually are:
Our company managed to establish a trusted circle as well, so every employee gets full access to all code and most of our systems. There is still a significant difference between us and Github - we don't just build a single product, we build <strong>product</strong> for <strong>clients</strong>. :pray: 

So every software project belongs to an specific "owner". Which fits pretty well in the Github project/organisation structure. A organisation just represents one of our clients and every project will get its own repository! Perfect! But...
- How can I grant access to a client for their own code?
- What shall we do with "external" developers?

I can't just simply grant access to all clients code each of my clients . And I cannot grant full access to our code to external developers, which are only here for a single project. Both of them don't receive the same level of trust and that would be a major difference between the our organisational model and yours.

So apart from the default "User can see everything and might get part of an organisation" (which perfectly fits companies which develop a product internally, which perfectly fits the open-source market), I'd request another privilege level of "User can see nothing until part of an organisation" for service oriented companies with many clients (this might as well fit larger cooperations and enterprises, I guess?). 

Regards, Stefan.

**Comment by dcwangmit01** [comment]
+1 to re-open this feature request:

We would like newly added users to our GHE instance to be assigned into two classes of permissions:
1) Most of our users should have default open, read-only code access to all public repositories in GHE regardless of organization membership (just like github.com).  This is the default.
2) A smaller subset of our users in GHE should have default no access to any code, unless specifically added to an organization and subsequent team.  This is a policy of least privilege, so that we can add 3rd party contractors to very specific repos, without marking all repos private which kills collaboration for our other trusted users.
