### ISSUE TITLE
About code ownership

### ISSUE THREAD

**Issue by kevincupp** [holman/feedback#650]
Hi Zach. I had a question about something you said in your _Move Fast and Break Nothing_ talk. On the subject of code ownership, that sounds great and certainly seems valuable for moving fast, but say someone leaves the company, is hit by a bus, or is otherwise unreachable, and something of theirs breaks, and no one knows how it works. Does this scenario ever cause problems? Or is it worth the problems simply because of the value you get and 98% of the time, that person is around to fix their stuff?

I'm curious to try this approach but always thought it was a good idea for all the developers to have some idea of how the rest of the application worked by getting their feet wet.

Thanks!

**Comment by holman** [comment]
Definitely important to lower your bus factor.

I think regardless of how you work, there's going to be some universal aspects that you need to pay heed to. A big part of that is documentation- you should document the system you're working on so that others can come in and help.

This is good for the company, of course, but it also serves some selfish purposes. If I'm sick, or out at a bar, or on vacation, I don't want to be the exclusive source of truth that people have to constantly drag me away from my life for.

This is pretty easy in a company the size of GitHub, but it can be a little tricky when you're ten people. There's a lot of things to do, and docs aren't necessarily first on everyone's minds. But getting at least something out there is super helpful even — especially? — at that small level.

The second thing you should look for is you should always aim to hire employees who won't ever die. Like, if you have coworkers that can take a bullet for you and live, that's legit, and this whole question is for naught.
