### ISSUE TITLE
GitHub Work Lifestyle

### ISSUE THREAD

**Issue by tejasmanohar** [holman/feedback#657]
Just a few questions about the "lifestyle" when you work at GitHub...

1. is GitHub a 9 to 5 type company, or does it just demand 8 hours a day and getting the job done from its remote, full-time employees?
2. Does GitHub allow work-study? How would they feel about a student working as say an engineer or support rep. for 6+ hours a day while studying?
3. Is age + education a big factor for hiring? Can experience, skills, and awesome projects outweigh a diploma from a top university or even post-bachelors education?
4. In your opinion, what are the most awesome benefits of working at GitHub?

**Comment by ttaylorr** [comment]
@holman does not work at GitHub. 



—

**Comment by holman** [comment]
I don't, but I'll say some of my thoughts in brief anyway:

> is GitHub a 9 to 5 type company

It is, but I don't think [companies should care about hours](http://zachholman.com/posts/how-github-works-hours/).

> Does GitHub allow work-study? How would they feel about a student working as say an engineer or support rep. for 6+ hours a day while studying?

We've had one or two employees that started part-time while they completed their studies (and we subsequently hired them full-time after graduation). They'll probably continue that trend as they grow.

> Is age + education a big factor for hiring? Can experience, skills, and awesome projects outweigh a diploma from a top university or even post-bachelors education?

When I started, I think half of the crew didn't graduate from college, and one or two didn't graduate high school. It's much easier to not give a fuck when the company is small, since doing the work is paramount. As the company grows, schooling becomes a metric for various good and bad reasons.

**Comment by tejasmanohar** [comment]
Alright, thanks for answering my questions @holman!
