### ISSUE TITLE
Have Github considered going ditching Rails and switching to a more performant tech stack?

### ISSUE THREAD

**Issue by Rawry** [holman/feedback#674]
Seeing projects like Stackoverflow bragging about how they run the whole thing on 5 servers and handling huge RPM numbers, or Twitter moving away from Rails and focusing more on JVM and Scala, I was always wondering if Github ever considered switching to Java stack (or other JVM-based language, or C# / C++ / Go, whatever) in order to handle the scale?

**Comment by holman** [comment]
Nope. Rails is great. You have to remember that from GitHub's perspective, the app layer is fairly irrelevant (I'm generalizing here) because we have to spend so long at the networked Git layer. So a ton of focus is spent on optimizing those networked calls and making that as fast as possible. All of that is written in C, via libgit2.

Beyond that, I think GitHub handled scaling pretty appropriately: use Ruby as long as you can because it's beautiful, and then when it becomes a major pain point, rewrite it in C or Go or something similar. They've been extracting services out in various languages for awhile now, slowly and deliberately when it makes sense.

**Comment by arthurnn** [comment]
> how they run the whole thing on 5 servers and handling huge RPM numbers

Was that a April 1st joke? :trollface:

**Comment by Rawry** [comment]
@arthurnn 
http://highscalability.com/blog/2014/7/21/stackoverflow-update-560m-pageviews-a-month-25-servers-and-i.html

Ok, not 5, but 25. Still very impressive IMO

**Comment by iamsreeju** [comment]
"Twitter moving away from Rails and focusing more on JVM and Scala"

Came across this now only. What Twitter designed earlier for and what they became need to be considered. They changed themselves as a realtime broadcasting system. Of course they had to move from Rails as it was not designed for that purpose. That introduced in Rails later in 5th version I think. So Twitter's requirement changed, so they switched to something, that doesn't mean Rails is not perfect, only imbeciles will say that. Any framework will be perfect when you use that for the specific purpose that designed for.
