### ISSUE TITLE
OS X Photos App

### ISSUE THREAD

**Issue by sharat** [holman/feedback#679]
What's your take on Photos App? Are you going to continue with Aperture or switch over? Or something else like Lightroom?

https://www.apple.com/osx/photos/

**Comment by holman** [comment]
I think it’s one of the greatest technological shifts I’ve experienced in the last three years.

Okay, that’s a bit of a wankery sentence, but I really mean it. We’ve been waiting for Apple to get us to this idealized and effortless cloud photo solution for quite some time, now, and cool, we’re here. But the really cool part is that it’s changed my habits as a photographer.

As a quick step back: I’m pretty squarely in the prosumer era of photography right now. I definitely enjoy shooting photos, and I shoot and edit them a lot more frequently than many of my casual friends, but all my photographer friends are certainly better at all of this than I am. So my needs are in this weird grey area.

Previously I used Aperture which, to be honest, was probably a bit more than I needed. Part of the problem was that Aperture was a product of mid-2000 era Apple, with all the baggage associated with that. It wasn’t a fun product to use in the last two years.

Photos is different. It’s obviously copped much of its design language (well, really, the entire app) from iOS, so it’s a lot more focused and simple. Coming from Aperture, I thought I’d be super worried about this. But all things considered, Photos has some pretty powerful adjustments and editing tucked away inside it if you know how to use it. I think it’s a pretty good balance.

The important stuff for me, though, is the library. I have 23k photos, and it’s kind of neat to have them on all of my devices without having to sync. But the *real* amazing part is that I can do full desktop-level editing on my phone and on my iPad. Part of that stems from using the same UI everywhere, part of that stems from the thumbnails-and-originals scheme they’re using. But this is a pretty subtle and powerful point people miss.

We always wanted the ability to be able to have our work on our phone, or our contacts on our desktop, or any number of permutation here. For the first time, though, I’m noticing that I don’t really care where *work* happens. If I’m in a Slack channel, for example, I’m cognizant that things are a little harder to do on my phone compared to the desktop app. With Photos, I don’t really feel that at all.

The result of this is that I can sit in an Uber and edit the photos that came out of my real camera. Typically the groan you hear is that you shoot tons of photos, but you never have the time to edit them. Now I can. And that’s really, really important to me.

Beyond that, I think the new iOS/OS X Photo Extensions APIs are going to be amazing. The few apps I’ve been using on my phone have really opened my eyes to how great it is to have the option to non-destructively edit your photos in a more unique way than Photos.app presents to me by default. I’m really stoked to see what abilities I can do on OS X once they open those APIs up as well.

There’s certainly a lot of warts left. I’ve been on the Photos beta since day one and my library refused to sync at all on OS X during half of the beta. (Even stranger, it started to work all of the sudden one day, without any changes made on my end.) So that’s a little worrisome. Because of that, the fact that I can’t easily make backups from my Mac (once I pull the pin and click “Optimize disk space” there too) is super frightening. I’d love to be able to hook up a hard drive or have Time Machine suck it all down from time to time, too. I don’t think iCloud will necessarily *lose* my data, but the fear of fat-fingering a setting and accidentally deleting my whole library myself is a little troublesome. Beyond that, GPS is non-existent (almost) in Photos.app, although that seems like an obvious addition in an upcoming point update.

So yeah, there’s technical problems yet, but I’m sold. I love it. It’s fast on my machine and my library, and when it works, it works great. I think about a year from now we can have another discussion on all of this and everything will be feeling really great.

After all the foul-starts on iCloud and .Mac, Apple might have finally cracked this nut. (Although now that I said that, I’m sure I’m going to regret saying that. Oh well, yolo.)

**Comment by sharat** [comment]
Hey @holman Thank you so much for writing it in detail :smile: 

:+1: 
> The important stuff for me, though, is the library. I have 23k photos, and it’s kind of neat to have them on all of my devices without having to sync. But the real amazing part is that I can do full desktop-level editing on my phone and on my iPad. Part of that stems from using the same UI everywhere, part of that stems from the thumbnails-and-originals scheme they’re using. But this is a pretty subtle and powerful point people miss.

I have pretty low SSD storage on my Mac and my photos have spanned across multiple libraries. I really hate tucking in my external drive to get my photos back. iCloud Photo Library could be a great solution! I am still not 100% to put everything on cloud! It scares me at this point. Also, Photos is light and fast!

I would have been more than happy to use Dropbox with this. Unfortunately nothing exists there with same no-destructive editing power. 

:+1: 
> I don't need to block off an hour to edit; I can do them a couple at a time, when I have time.

Absolutely this is something really works. It's far more convenient to use phone or iPad for editing over pulling out a laptop when you're in airplane or Uber.
