### ISSUE TITLE
How do you make progress?

### ISSUE THREAD

**Issue by davezych** [holman/feedback#696]
In issue 690, in your last bullet point you made comments such as `Keep asking questions of yourself` and `If you're not learning, you're treading water`. What questions do you ask yourself and how do you learn things? Do you just dick around with languages/technologies/frameworks and build dumb shit or do you watch videos and read tutorials and read blog posts by smart people?

**Comment by holman** [comment]
/cc #690 

>  What questions do you ask yourself and how do you learn things? Do you just dick around with languages/technologies/frameworks and build dumb shit or do you watch videos and read tutorials and read blog posts by smart people?

It's kind of binary for me — I think you kind of just know. At various points in my career I've realized, *wow, I've certainly changed a lot in the last year*, be it technically or organizationally or otherwise. I think that's a good realization. If you end up saying *man, there's really nothing in the last year that I learned that was new or interesting*, well then, you have a problem, imo. Certainly there are gradients — some years are more illuminating than others — but in my experience it's fairly stark.

If it doesn't seem super obvious to you, then you're probably doing alright.
