### ISSUE TITLE
What do you say to the folks who think Ruby is dying?

### ISSUE THREAD

**Issue by zmrow** [holman/feedback#698]
You've probably heard this / read this / scoffed at this but I'm really curious...  Folks in my organization are not all that familiar with Ruby and though I've been championing it we seem to be moving towards Python...  "Python seems to be the language everyone is moving too..."

So what do you think about the overall climate in the industry right now?  Ruby is mature now, but languages like Go and Rust seem to be gaining a lot of traction (or maybe it's just the whole "OOOH NEW LANGUAGE" hype).

Thoughts?

**Comment by holman** [comment]
I can't remember who said it initially, but my favorite sentiment on all this is:

> The only people still using Ruby are the ones making money.

In other words, I think it's a pretty great, stable community of people who use it in production and have seen it all, so to speak. I kind of include Python in this, too- besides the obvious syntactical similarities, I think they are pretty similar in terms of ideology.

I'm in a bit of my third honeymoon with Ruby (and Rails) this summer. I've been seeing a lot of people in the Go community, for example, talk about "just use the http libraries, no one needs a framework" and I think they're fucking bonkers, or at the very least write backend apps with no UI and no more than two contributors on the project. Frameworks like Rails give you so many security, development, and deployment niceties that I have zero interest in rolling my own anymore. (I saw a "screw frameworks" Go talk that spent *ten minutes* on how to reload code in development, for example... that was a solved problem for me in 2005.)

I'm kind of in love with the idea of writing everything in Ruby (or something similar) and when it makes sense and can be provably improved, extract it out in something like Go or C. The Go+Ruby combination in particular is super attractive to me, and it's likely going to be fine for the foreseeable future, I think.

**Comment by sharat** [comment]
The recent post from Parse Engineering Team - [How We Moved Our API From Ruby to Go and Saved Our Sanity](http://blog.parse.com/learn/how-we-moved-our-api-from-ruby-to-go-and-saved-our-sanity/) 

if you look at GitHub also, the number of Ruby repos are getting lower over these months. In my personal experience, it's very hard to find skilled Ruby developers and they're very expensive too! 

I am wondering what's will be the next language gonna rule like PHP. Though there are JS tech is in the peak, I still not convinced to use it on server side. Go and Rust looks promising.

**Comment by holman** [comment]
>The recent post from Parse Engineering Team [...] if you look at GitHub also, the number of Ruby repos are getting lower over these months.

I think looking at these examples don't the whole picture here. GitHub, for example, is a fairly feature-complete product, and their next few years will likely focus on optimization work. If you have a mature product, you have a very clear performance profile of what's breaking, what's fast, and what's slow. That's why GitHub, a seven year old company, is more likely to open source Go libraries at this stage of its life rather than Ruby libraries (for example)- it's obvious which use cases can be targeted for speed, maintainability, and shareability.

Parse is another clear example of this- they have a codebase that they've worked with for quite some time, with obvious spots of improvement, so they switched to Go. If you're looking at new companies that need a fair bit of creativity, product development, and development speed, I think Ruby makes a lot of sense. Premature optimization is not just a waste of time, it's an *exponential* waste of time, as you might head in a wrong product direction that can potentially sink the entire company.

> I am wondering what's will be the next language gonna rule like PHP. Though there are JS tech is in the peak, I still not convinced to use it on server side. Go and Rust looks promising.

I'm really the wrong person to ask here, but I can't really imagine anything taking over like PHP did for the next five years or so. That was a pretty meteoric explosion, and there weren't a lot of clear and open source options fifteen years ago. I don't see JavaScript development being a flash in the pan, I think Go is clearly going to continue to increase in popularity, and I think languages like Ruby and Python and PHP will probably hit a decent cruising speed for the time being. Even .Net technologies have a brighter future ahead of them again. There's a lot of choice right now, there's a lot of resources flooding into open source from companies who clearly want to compete in the community, and there's a ton of stealing of good ideas between communities rather than getting siloed off in the past.

A decade from now, yeah, things may be completely different, but for the time being there's a lot of exciting choices and options happening. Kind of love it.

**Comment by hodiseev** [comment]
Hi, I have seen this discussion re-emerging again and again so I made my own research. Unfortunately too much hassle to copy it all here but whoever wants to share his view, very welcome to do it: http://odiseev.com/2016/08/10/is-ruby-dying/

Enjoy!
