### ISSUE TITLE
Would you recommend working for GitHub ?

### ISSUE THREAD

**Issue by xoco70** [holman/feedback#855]
Hi Zach, 

Right now, I just began a new job 2 monthes ago, I work in a small startup around Solar Energy, Blockchain and IoT. I like my new job.

Recently, I was contacted on LinkedIn by HR asking me if I were interested to begin a process for a Solution Engineering position. I have never work in this kind of position, but I had a great contact with the manager, and I feel quite excited when I think about GitHub. 

I don't know if I will go through the whole GitHub hiring process, as it must be a very selective process, but I am interested in your opinion. Would you recommend working for Github ?

**Comment by holman** [comment]
It's a pretty known quantity at this point, imo. Microsoft is a large company. They make money, so there's less risk, they're good on a resume, they're slow to market, there's a lot of hierarchy and managers, compensation is probably decent.

I don't really have any advice on whether I recommend someone work there... it really depends on your circumstance. I know someone just recently got hired after doing a bunch of startups because they wanted to chill and not have to do much anymore- that's totally cool. I wouldn't recommend it for myself, but then again I don't want to work at a company like that again anyway. Really just depends on what you're looking to get out of your time there, and if it's a better option than other places you could work at.

**Comment by xoco70** [comment]
Nice Answer !

**Comment by xoco70** [comment]
If you get depressed again in your life, go to México, it is full of colors!
