### ISSUE TITLE
Where to report any bug we found on github?

### ISSUE THREAD

**Issue by kamalpreet-singh18** [holman/feedback#873]
I was going through my profile page on Github and I found one bug. I know this is not the place to report the bug but I want to know where can I report it.

**Comment by hakusaro** [comment]
Apologies, but it's been a moment or two since Holman has been with GitHub. You should contact GitHub here to report bugs: https://github.com/contact.

I really cannot understate just how awesome Holman's blog is! You should check it out and read some of his posts -- they're really quite stunning: https://zachholman.com/.
