### ISSUE TITLE
What do you think about Conventional Commits?

### ISSUE THREAD

**Issue by gepgecici** [holman/feedback#875]
I have been using Conventional Commits for a while and I'm enjoying it for now. It provides me really good commit history, the only problem I have experience is I sometimes cannot find the best type with scope value.

As far as I can tell, you don't adapt it. Is there a reason for that? or do you plan to adapt anytime soon?

**Comment by holman** [comment]
Honestly hadn’t heard about it yet!

It looks pretty decent, all in all. I’m not entirely sure about the “lightweight” part of it, although I do appreciate that it models itself off of the suggested Git commit style.

My own opinion is a little bit different: https://zachholman.com/posts/git-commit-history/

Basically, I think the relevant aspect is the pull request rather than the commits themselves, although this is slightly less relevant now that rebasing is more of a thing in GitHub the product.

I don’t think I’d use Conventional Commits any time soon, though.

**Comment by taylortrimble** [comment]
I won't use this either, but saving people a few clicks: https://www.conventionalcommits.org
