### ISSUE TITLE
What do you think of the autonomous driving market in this decade?

### ISSUE THREAD

**Issue by marswong** [holman/feedback#886]
- Which company will drive this market?
- Which product will bring great values to society?
- Would you invest on this market haha?

**Comment by holman** [comment]
> Which company will drive this market?

I'm biased since I own a Tesla, but I'm fairly bought into the idea that they'll crack it first. I think having their network really does help them get into the very long tail better than other approaches. That said... I don't know if they'll necessarily get there any time soon. It's a tough problem.

> Which product will bring great values to society?

Getting to Level 5 would change a lot of things, I'd imagine. Obviously your own car and a ride share would benefit from it, but also just kind of rethinking car ownership in general would be pretty interesting (and a big change in society's values, at least in America). There's a lot to be said for product delivery, too (both last mile and longer trips, like cross-country, for example).

> Would you invest on this market haha?

Ha, of course. It's not really in my investment wheelhouse, but always would be interested in the area.

**Comment by dmellstrom** [comment]
eww
